task: davis
contrastive_split: within

drug_featurizer: MorganFeaturizer
target_featurizer: ProtBertFeaturizer
model_architecture: SimpleCoembedding
latent_dimension: 1024
latent_distance: "Cosine"

batch_size: 16
contrastive_batch_size: 256
shuffle: True
num_workers: 0

epochs: 50
every_n_val: 1
lr: 1e-4
lr_t0: 10
clr: 1e-5
clr_t0: 10

replicate: 0
device: 5
verbosity: 3

wandb_proj: contrastive_TEST
log_file: ./logs/davis_contrastive_largeBatch.log
model_save_dir: ./best_models
